package es.us.dp1.lx_xy_24_25.your_game_name.statistic;

public enum Metric {
    GAMES_PLAYED,
    VICTORIES,
    DEFEATS,
    WIN_RATE,
    TOTAL_PLAY_TIME,
    AVERAGE_DURATION,
    SHORTEST_GAME,
    LONGEST_GAME,
    TOTAL_CARDS_USED,
    POWER_CARDS_USED,
    AVERAGE_CARDS_PER_GAME,
    MAX_LINE_LENGTH,
    TOTAL_LINES_COMPLETED,
    AVERAGE_LINE_LENGTH,
    COMPLETED_PUZZLES,
    HIGHEST_SCORE_PUZZLE,
    TOTAL_PUZZLE_SCORE,
    AVERAGE_PUZZLE_SCORE,
    TOTAL_SCORE,
    HIGHEST_SCORE,
    LOWEST_SCORE,
    AVERAGE_SCORE,
    MESSAGES_SENT,
    FRIENDS_COUNT
}